"""Regenerate lib/stocknames.py from an installed game.

    python devtools\\mknames.py

A weapon folder is named after the model, not the weapon: the Hardedge sits
in WE0000_02_Cloud_HardBreaker, and six of Cloud's twelve are called
END2Weapon1 through END2Weapon6. The game's own English text has the real
names, so repoint.py offers those instead of the folder's spelling. This is
what reads them out.

Costumes are not here. The game names only the handful its outfit menu
offers, and those names ("Ex-SOLDIER: First Class" for the default) say less
to someone picking a slot than the folder's own word does, so slots.py
spaces the folder tail into words and leaves it at that.

A dev tool: it is not part of a release, and nothing at runtime calls it.
"""
import os
import re
import struct
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)
sys.path.insert(0, os.path.join(REPO, "lib"))

import config                                                   # noqa: E402
import slots                                                    # noqa: E402
import stockgraft                                               # noqa: E402

OUT = os.path.join(REPO, "lib", "stocknames.py")

# Where the English text lives. Container paths are relative to /Game/.
TEXT = "Text/US/Resident_TxtRes.uasset"

# Which weapon type belongs to which character. The game keys a weapon's
# name by TYPE and number -- $Item_W_TSW_0001 -- and nothing in the data
# links that to a model folder, so the pairing is written down here and
# checked below against the folder the game actually keeps the weapon in.
CHARACTER = {
    "TSW": "WE0000",        # Cloud, greatswords
    "GUN": "WE0001",        # Barret, gun-arms
    "GLV": "WE0002",        # Tifa, gloves
    "ROD": "WE0003",        # Aerith, staves
    "CLR": "WE0004",        # Red XIII, collars
    "SHR": "WE0005",        # Yuffie, shuriken
    "MGP": "WE0007",        # Cait Sith, megaphones
}

HEADER = '''"""
stocknames.py -- what FFVII Rebirth calls its weapons.

GENERATED by devtools/mknames.py out of the game's own English text. Do not
edit by hand; regenerate after a game update that adds weapons.

Keyed by slot id, because a weapon's folder name is the MODEL's name and the
two often differ: WE0000_02_Cloud_HardBreaker is the Hardedge, and Cloud's
six late weapons are filed as END2Weapon1..6. slots.label() prefers this
table and falls back to the folder's own words -- which is what every weapon
absent from here (an enemy's, an NPC's) gets.
"""

'''


def text_resource():
    """The game's English text asset, as bytes."""
    for u in stockgraft._utocs():
        try:
            toc = stockgraft._toc(u)
        except Exception:
            continue
        for index, path in toc.paths.items():
            if path.replace("\\", "/") == TEXT:
                return toc.read(index)
    sys.exit(f"no {TEXT} in the game containers")


def read_string(data, at):
    """One length-prefixed string. A NEGATIVE length means UTF-16, and the
    count is of characters rather than bytes -- Járngreipr and Brísingamen
    are stored that way."""
    length = struct.unpack_from("<i", data, at)[0]
    if length >= 0:
        return data[at + 4:at + 4 + max(0, length - 1)].decode("utf-8")
    chars = -length
    return data[at + 4:at + 4 + chars * 2 - 2].decode("utf-16-le")


def weapon_names(data):
    """{item key -> name} for every weapon in the text resource.

    A record is key, then name, then a count and that many extra forms (the
    article, the plural, the lowercase singular). Only the first two are
    wanted, so the records are found by their keys rather than walked.
    """
    out = {}
    for m in re.finditer(rb"\$Item_W_([A-Z]{3})_(\d{4})\x00", data):
        start = m.start() - 4
        if start < 0:
            continue
        if struct.unpack_from("<i", data, start)[0] != m.end() - m.start():
            continue                    # not a string, just those bytes
        name = read_string(data, m.end())
        if name:
            out[(m.group(1).decode(), int(m.group(2)))] = name
    return out


def slot_of(number):
    """The model slot a weapon's number belongs to.

    Numbering runs 0001-0006 for the weapons carried over from the first
    game and 0101-0106 for this one's, and the folders follow in the same
    order from _00 and from _11. Every pairing that produces is corroborated
    by the folder's own name where the two happen to agree -- Iron Blade in
    WE0000_01_Cloud_IronBlade, Boomerang in WE0005_01_Yuffie_Boomerang.
    """
    return number - 1 if number < 100 else 10 + (number - 100)


def words(text):
    return re.sub(r"(?<=[a-z])(?=[A-Z])", " ", text).lower().split()


def check(named, stock):
    """Refuse a type whose first weapon lands in a folder named after
    something else -- that is what a wrong CHARACTER entry looks like, and it
    would mislabel a whole character's list."""
    bad = []
    for kind, prefix in sorted(CHARACTER.items()):
        first = named.get(f"{prefix}_00")
        folder = stock.get(f"{prefix}_00")
        if not first or not folder:
            bad.append(f"{kind}: nothing at {prefix}_00")
        elif not set(words(first)) & set(words(folder.split("_", 3)[3])):
            bad.append(f"{kind}: called {first!r} but the folder is {folder}")
    return bad


def main():
    if not config.GAME_DIR:
        sys.exit("no game installed -- this reads the names out of it")
    found = weapon_names(text_resource())
    if not found:
        sys.exit("read no weapon names -- the text resource has changed shape")

    stock = {f[:9]: f for f in slots.stock(slots.WEAPON)}
    named, skipped = {}, []
    for (kind, number), name in sorted(found.items()):
        prefix = CHARACTER.get(kind)
        if not prefix:
            continue                    # Masamune and the like: no slot
        sid = f"{prefix}_{slot_of(number):02}"
        if sid not in stock:
            skipped.append(f"{kind}_{number:04} ({name}): no {sid} folder")
            continue
        named[sid] = name

    bad = check(named, stock)
    if bad:
        sys.exit("\n".join(["the weapon-to-folder pairing does not hold:"]
                           + [f"  {b}" for b in bad]))

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER)
        f.write("WEAPONS = {\n")
        for sid in sorted(named):
            f.write(f'    "{sid}": "{named[sid]}",\n')
        f.write("}\n")
    for s in skipped:
        print(f"  left out: {s}")
    print(f"{OUT}: {len(named)} weapons named, "
          f"{len(stock) - len(named)} left to their folder names")


if __name__ == "__main__":
    main()
