"""Regenerate lib/stockslots.py from an installed game.

    python devtools\\mkslots.py

The list of costumes and weapons the game ships is the same on every install,
so repoint.py carries a copy and does not need the game to offer a menu. This
is what produces that copy -- run it after a game update that adds costumes,
and check the diff before committing.

A dev tool: it is not part of a release, and nothing at runtime calls it.
"""
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)
sys.path.insert(0, os.path.join(REPO, "lib"))

import config                                                   # noqa: E402
import slots                                                    # noqa: E402

OUT = os.path.join(REPO, "lib", "stockslots.py")

HEADER = '''"""
stockslots.py -- the costumes and weapons FFVII Rebirth ships with.

GENERATED by devtools/mkslots.py from an installed game. Do not edit by
hand; regenerate after a game update that adds costumes.

Only folder NAMES are listed. Each holds its mesh at Model/<slot id>, the
slot id being the folder's own first nine characters, so nothing else has
to be recorded.

This exists so repoint.py can offer its menu on a machine with no game
installed -- the list is identical on every install. slots.stock() still
prefers the real thing when it is there, so a game update that adds a
costume works before this file catches up.
"""

'''


def emit(name, folders):
    out = [f"{name} = ["]
    for f in folders:
        out.append(f'    "{f}",')
    out.append("]")
    return "\n".join(out)


def main():
    if not config.GAME_DIR:
        sys.exit("no game installed -- this reads the list out of it")
    costumes = sorted(slots.stock(slots.COSTUME))
    weapons = sorted(slots.stock(slots.WEAPON))
    if not costumes or not weapons:
        sys.exit(f"read {len(costumes)} costumes and {len(weapons)} weapons "
                 "-- that is not a whole game")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER)
        f.write(emit("COSTUMES", costumes))
        f.write("\n\n")
        f.write(emit("WEAPONS", weapons))
        f.write("\n")
    print(f"{OUT}: {len(costumes)} costumes, {len(weapons)} weapons")


if __name__ == "__main__":
    main()
